// Countries prioritized for BomaVibes' Francophone-Africa-first rollout.
// Adding a new country later is just appending an object here — no other
// code needs to change. `regions: []` is valid for a country not yet
// mapped in detail (the picker will simply skip straight to a free city
// entry for that country until regions are added).

export const COUNTRIES = [
  {
    code: 'GA',
    name: 'Gabon',
    flag: '🇬🇦',
    continent: 'Afrique',
    regions: [
      { name: 'Estuaire', cities: ['Libreville', 'Akanda', 'Owendo', 'Ntoum'] },
      { name: 'Haut-Ogooué', cities: ['Franceville', 'Moanda', 'Okondja'] },
      { name: 'Moyen-Ogooué', cities: ['Lambaréné', 'Ndjolé'] },
      { name: 'Ngounié', cities: ['Mouila', 'Fougamou', 'Mbigou'] },
      { name: 'Nyanga', cities: ['Tchibanga', 'Mayumba'] },
      { name: 'Ogooué-Ivindo', cities: ['Makokou', 'Booué', 'Mékambo'] },
      { name: 'Ogooué-Lolo', cities: ['Koulamoutou', 'Lastourville', 'Pana'] },
      { name: 'Ogooué-Maritime', cities: ['Port-Gentil', 'Gamba', 'Omboué'] },
      { name: 'Woleu-Ntem', cities: ['Oyem', 'Bitam', 'Mitzic'] },
    ],
  },
  {
    code: 'CM',
    name: 'Cameroun',
    flag: '🇨🇲',
    continent: 'Afrique',
    regions: [
      { name: 'Centre', cities: ['Yaoundé', 'Mbalmayo', 'Obala'] },
      { name: 'Littoral', cities: ['Douala', 'Nkongsamba', 'Édéa'] },
      { name: 'Ouest', cities: ['Bafoussam', 'Dschang', 'Mbouda'] },
      { name: 'Nord-Ouest', cities: ['Bamenda', 'Kumbo'] },
      { name: 'Sud-Ouest', cities: ['Buea', 'Limbe', 'Kumba'] },
      { name: 'Nord', cities: ['Garoua', 'Guider'] },
      { name: 'Extrême-Nord', cities: ['Maroua', 'Kousséri'] },
      { name: 'Adamaoua', cities: ['Ngaoundéré', 'Meiganga'] },
      { name: 'Est', cities: ['Bertoua', 'Abong-Mbang'] },
      { name: 'Sud', cities: ['Ebolowa', 'Kribi', 'Sangmélima'] },
    ],
  },
  {
    code: 'CG',
    name: 'Congo',
    flag: '🇨🇬',
    continent: 'Afrique',
    regions: [
      { name: 'Brazzaville', cities: ['Brazzaville'] },
      { name: 'Pointe-Noire', cities: ['Pointe-Noire'] },
      { name: 'Niari', cities: ['Dolisie', 'Loudima'] },
      { name: 'Bouenza', cities: ['Nkayi', 'Madingou'] },
      { name: 'Cuvette', cities: ['Owando', 'Boundji'] },
      { name: 'Cuvette-Ouest', cities: ['Ewo'] },
      { name: 'Kouilou', cities: ['Hinda', 'Madingo-Kayes'] },
      { name: 'Lékoumou', cities: ['Sibiti'] },
      { name: 'Likouala', cities: ['Impfondo', 'Dongou'] },
      { name: 'Plateaux', cities: ['Djambala', 'Gamboma'] },
      { name: 'Pool', cities: ['Kinkala', 'Mindouli'] },
      { name: 'Sangha', cities: ['Ouesso', 'Sembé'] },
    ],
  },
  {
    code: 'CD',
    name: 'RDC',
    flag: '🇨🇩',
    continent: 'Afrique',
    regions: [
      { name: 'Kinshasa', cities: ['Kinshasa'] },
      { name: 'Kongo-Central', cities: ['Matadi', 'Boma', 'Muanda'] },
      { name: 'Nord-Kivu', cities: ['Goma', 'Butembo', 'Beni'] },
      { name: 'Sud-Kivu', cities: ['Bukavu', 'Uvira'] },
      { name: 'Haut-Katanga', cities: ['Lubumbashi', 'Likasi', 'Kipushi'] },
      { name: 'Lualaba', cities: ['Kolwezi'] },
      { name: 'Kasaï', cities: ['Tshikapa'] },
      { name: 'Kasaï-Central', cities: ['Kananga'] },
      { name: 'Kasaï-Oriental', cities: ['Mbuji-Mayi'] },
      { name: 'Tshopo', cities: ['Kisangani'] },
      { name: 'Ituri', cities: ['Bunia'] },
      { name: 'Équateur', cities: ['Mbandaka'] },
    ],
  },
  {
    code: 'CI',
    name: "Côte d'Ivoire",
    flag: '🇨🇮',
    continent: 'Afrique',
    regions: [
      { name: 'Abidjan', cities: ['Abidjan'] },
      { name: 'Yamoussoukro', cities: ['Yamoussoukro'] },
      { name: 'Bas-Sassandra', cities: ['San-Pédro', 'Sassandra'] },
      { name: 'Comoé', cities: ['Abengourou', 'Agnibilékrou'] },
      { name: 'Denguélé', cities: ['Odienné'] },
      { name: 'Gôh-Djiboua', cities: ['Gagnoa', 'Divo'] },
      { name: 'Lacs', cities: ['Dimbokro', 'Bongouanou'] },
      { name: 'Lagunes', cities: ['Dabou', 'Grand-Bassam'] },
      { name: 'Montagnes', cities: ['Man', 'Danané'] },
      { name: 'Sassandra-Marahoué', cities: ['Daloa', 'Vavoua'] },
      { name: 'Savanes', cities: ['Korhogo', 'Ferkessédougou'] },
      { name: 'Vallée du Bandama', cities: ['Bouaké', 'Katiola'] },
      { name: 'Woroba', cities: ['Séguéla', 'Mankono'] },
      { name: 'Zanzan', cities: ['Bondoukou', 'Bouna'] },
    ],
  },
  {
    code: 'SN',
    name: 'Sénégal',
    flag: '🇸🇳',
    continent: 'Afrique',
    regions: [
      { name: 'Dakar', cities: ['Dakar', 'Pikine', 'Guédiawaye', 'Rufisque'] },
      { name: 'Thiès', cities: ['Thiès', 'Mbour', 'Tivaouane'] },
      { name: 'Diourbel', cities: ['Diourbel', 'Touba', 'Mbacké'] },
      { name: 'Saint-Louis', cities: ['Saint-Louis', 'Richard-Toll'] },
      { name: 'Louga', cities: ['Louga', 'Kébémer'] },
      { name: 'Fatick', cities: ['Fatick', 'Gossas'] },
      { name: 'Kaolack', cities: ['Kaolack', 'Guinguinéo'] },
      { name: 'Kaffrine', cities: ['Kaffrine'] },
      { name: 'Tambacounda', cities: ['Tambacounda'] },
      { name: 'Kédougou', cities: ['Kédougou'] },
      { name: 'Kolda', cities: ['Kolda'] },
      { name: 'Sédhiou', cities: ['Sédhiou'] },
      { name: 'Ziguinchor', cities: ['Ziguinchor'] },
      { name: 'Matam', cities: ['Matam'] },
    ],
  },
  {
    code: 'BJ',
    name: 'Bénin',
    flag: '🇧🇯',
    continent: 'Afrique',
    regions: [
      { name: 'Littoral', cities: ['Cotonou'] },
      { name: 'Atlantique', cities: ['Abomey-Calavi', 'Ouidah'] },
      { name: 'Ouémé', cities: ['Porto-Novo', 'Sèmè-Podji'] },
      { name: 'Plateau', cities: ['Sakété', 'Pobè'] },
      { name: 'Zou', cities: ['Abomey', 'Bohicon'] },
      { name: 'Collines', cities: ['Savalou', 'Dassa-Zoumè'] },
      { name: 'Borgou', cities: ['Parakou', 'Nikki'] },
      { name: 'Alibori', cities: ['Kandi', 'Malanville'] },
      { name: 'Atacora', cities: ['Natitingou', 'Tanguiéta'] },
      { name: 'Donga', cities: ['Djougou', 'Bassila'] },
      { name: 'Couffo', cities: ['Aplahoué', 'Dogbo'] },
      { name: 'Mono', cities: ['Lokossa', 'Comè'] },
    ],
  },
  {
    code: 'TG',
    name: 'Togo',
    flag: '🇹🇬',
    continent: 'Afrique',
    regions: [
      { name: 'Maritime', cities: ['Lomé', 'Aného', 'Tsévié'] },
      { name: 'Plateaux', cities: ['Atakpamé', 'Kpalimé'] },
      { name: 'Centrale', cities: ['Sokodé', 'Sotouboua'] },
      { name: 'Kara', cities: ['Kara', 'Bassar'] },
      { name: 'Savanes', cities: ['Dapaong', 'Mango'] },
    ],
  },
  {
    code: 'ML',
    name: 'Mali',
    flag: '🇲🇱',
    continent: 'Afrique',
    regions: [
      { name: 'Bamako', cities: ['Bamako'] },
      { name: 'Kayes', cities: ['Kayes', 'Kita'] },
      { name: 'Koulikoro', cities: ['Koulikoro', 'Kati'] },
      { name: 'Sikasso', cities: ['Sikasso', 'Koutiala'] },
      { name: 'Ségou', cities: ['Ségou', 'San'] },
      { name: 'Mopti', cities: ['Mopti', 'Djenné'] },
      { name: 'Tombouctou', cities: ['Tombouctou'] },
      { name: 'Gao', cities: ['Gao'] },
      { name: 'Kidal', cities: ['Kidal'] },
    ],
  },
  {
    code: 'BF',
    name: 'Burkina Faso',
    flag: '🇧🇫',
    continent: 'Afrique',
    regions: [
      { name: 'Centre', cities: ['Ouagadougou'] },
      { name: 'Hauts-Bassins', cities: ['Bobo-Dioulasso'] },
      { name: 'Boucle du Mouhoun', cities: ['Dédougou'] },
      { name: 'Cascades', cities: ['Banfora'] },
      { name: 'Centre-Est', cities: ['Tenkodogo'] },
      { name: 'Centre-Nord', cities: ['Kaya'] },
      { name: 'Centre-Ouest', cities: ['Koudougou'] },
      { name: 'Centre-Sud', cities: ['Manga'] },
      { name: 'Est', cities: ['Fada N\'Gourma'] },
      { name: 'Nord', cities: ['Ouahigouya'] },
      { name: 'Plateau-Central', cities: ['Ziniaré'] },
      { name: 'Sahel', cities: ['Dori'] },
      { name: 'Sud-Ouest', cities: ['Gaoua'] },
    ],
  },
  {
    code: 'NE',
    name: 'Niger',
    flag: '🇳🇪',
    continent: 'Afrique',
    regions: [
      { name: 'Niamey', cities: ['Niamey'] },
      { name: 'Agadez', cities: ['Agadez', 'Arlit'] },
      { name: 'Diffa', cities: ['Diffa'] },
      { name: 'Dosso', cities: ['Dosso'] },
      { name: 'Maradi', cities: ['Maradi'] },
      { name: 'Tahoua', cities: ['Tahoua', 'Birni-N\'Konni'] },
      { name: 'Tillabéri', cities: ['Tillabéri'] },
      { name: 'Zinder', cities: ['Zinder'] },
    ],
  },
  {
    code: 'MA',
    name: 'Maroc',
    flag: '🇲🇦',
    continent: 'Afrique',
    regions: [
      { name: 'Casablanca-Settat', cities: ['Casablanca', 'Settat', 'Mohammédia'] },
      { name: 'Rabat-Salé-Kénitra', cities: ['Rabat', 'Salé', 'Kénitra'] },
      { name: 'Fès-Meknès', cities: ['Fès', 'Meknès'] },
      { name: 'Marrakech-Safi', cities: ['Marrakech', 'Safi', 'Essaouira'] },
      { name: 'Tanger-Tétouan-Al Hoceïma', cities: ['Tanger', 'Tétouan'] },
      { name: 'Oriental', cities: ['Oujda', 'Nador'] },
      { name: 'Souss-Massa', cities: ['Agadir', 'Taroudant'] },
      { name: 'Béni Mellal-Khénifra', cities: ['Béni Mellal', 'Khénifra'] },
      { name: 'Drâa-Tafilalet', cities: ['Errachidia', 'Ouarzazate'] },
      { name: 'Guelmim-Oued Noun', cities: ['Guelmim'] },
      { name: 'Laâyoune-Sakia El Hamra', cities: ['Laâyoune'] },
      { name: 'Dakhla-Oued Ed-Dahab', cities: ['Dakhla'] },
    ],
  },
  {
    code: 'DZ',
    name: 'Algérie',
    flag: '🇩🇿',
    continent: 'Afrique',
    regions: [
      { name: 'Alger', cities: ['Alger', 'Bab Ezzouar', 'Hydra'] },
      { name: 'Oran', cities: ['Oran', 'Es Senia', 'Bir El Djir'] },
      { name: 'Constantine', cities: ['Constantine', 'El Khroub'] },
      { name: 'Annaba', cities: ['Annaba', 'El Bouni'] },
      { name: 'Blida', cities: ['Blida', 'Boufarik'] },
      { name: 'Tlemcen', cities: ['Tlemcen', 'Maghnia'] },
      { name: 'Sétif', cities: ['Sétif', 'El Eulma'] },
      { name: 'Béjaïa', cities: ['Béjaïa', 'Akbou'] },
      { name: 'Batna', cities: ['Batna', 'Barika'] },
      { name: 'Tizi Ouzou', cities: ['Tizi Ouzou', 'Azazga'] },
      { name: 'Ouargla', cities: ['Ouargla', 'Hassi Messaoud'] },
      { name: 'Ghardaïa', cities: ['Ghardaïa', 'Metlili'] },
    ],
  },
  {
    code: 'TN',
    name: 'Tunisie',
    flag: '🇹🇳',
    continent: 'Afrique',
    regions: [
      { name: 'Tunis', cities: ['Tunis'] },
      { name: 'Ariana', cities: ['Ariana'] },
      { name: 'Ben Arous', cities: ['Ben Arous'] },
      { name: 'Manouba', cities: ['Manouba'] },
      { name: 'Nabeul', cities: ['Nabeul', 'Hammamet'] },
      { name: 'Sousse', cities: ['Sousse'] },
      { name: 'Monastir', cities: ['Monastir'] },
      { name: 'Mahdia', cities: ['Mahdia'] },
      { name: 'Sfax', cities: ['Sfax'] },
      { name: 'Kairouan', cities: ['Kairouan'] },
      { name: 'Bizerte', cities: ['Bizerte'] },
      { name: 'Gabès', cities: ['Gabès'] },
      { name: 'Médenine', cities: ['Médenine', 'Djerba'] },
      { name: 'Tozeur', cities: ['Tozeur'] },
      { name: 'Gafsa', cities: ['Gafsa'] },
    ],
  },
  {
    code: 'NG',
    name: 'Nigeria',
    flag: '🇳🇬',
    continent: 'Afrique',
    regions: [
      { name: 'Lagos', cities: ['Lagos', 'Ikeja', 'Lekki'] },
      { name: 'Federal Capital Territory', cities: ['Abuja'] },
      { name: 'Kano', cities: ['Kano'] },
      { name: 'Rivers', cities: ['Port Harcourt'] },
      { name: 'Oyo', cities: ['Ibadan'] },
      { name: 'Kaduna', cities: ['Kaduna'] },
      { name: 'Ogun', cities: ['Abeokuta'] },
      { name: 'Enugu', cities: ['Enugu'] },
      { name: 'Delta', cities: ['Warri', 'Asaba'] },
      { name: 'Anambra', cities: ['Awka', 'Onitsha'] },
      { name: 'Edo', cities: ['Benin City'] },
      { name: 'Plateau', cities: ['Jos'] },
      { name: 'Borno', cities: ['Maiduguri'] },
      { name: 'Cross River', cities: ['Calabar'] },
    ],
  },

  // Afrique
  { code: 'ZA', name: 'Afrique du Sud', flag: '🇿🇦', continent: 'Afrique', regions: [] },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', continent: 'Afrique', regions: [] },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', continent: 'Afrique', regions: [] },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', continent: 'Afrique', regions: [] },
  { code: 'CV', name: 'Cap-Vert', flag: '🇨🇻', continent: 'Afrique', regions: [] },
  { code: 'CF', name: 'République centrafricaine', flag: '🇨🇫', continent: 'Afrique', regions: [] },
  { code: 'KM', name: 'Comores', flag: '🇰🇲', continent: 'Afrique', regions: [] },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', continent: 'Afrique', regions: [] },
  { code: 'EG', name: 'Égypte', flag: '🇪🇬', continent: 'Afrique', regions: [] },
  { code: 'ER', name: 'Érythrée', flag: '🇪🇷', continent: 'Afrique', regions: [] },
  { code: 'ET', name: 'Éthiopie', flag: '🇪🇹', continent: 'Afrique', regions: [] },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', continent: 'Afrique', regions: [] },
  { code: 'GM', name: 'Gambie', flag: '🇬🇲', continent: 'Afrique', regions: [] },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', continent: 'Afrique', regions: [] },
  { code: 'GN', name: 'Guinée', flag: '🇬🇳', continent: 'Afrique', regions: [] },
  { code: 'GW', name: 'Guinée-Bissau', flag: '🇬🇼', continent: 'Afrique', regions: [] },
  { code: 'GQ', name: 'Guinée équatoriale', flag: '🇬🇶', continent: 'Afrique', regions: [] },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', continent: 'Afrique', regions: [] },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', continent: 'Afrique', regions: [] },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', continent: 'Afrique', regions: [] },
  { code: 'LY', name: 'Libye', flag: '🇱🇾', continent: 'Afrique', regions: [] },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', continent: 'Afrique', regions: [] },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', continent: 'Afrique', regions: [] },
  { code: 'MU', name: 'Maurice', flag: '🇲🇺', continent: 'Afrique', regions: [] },
  { code: 'MR', name: 'Mauritanie', flag: '🇲🇷', continent: 'Afrique', regions: [] },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', continent: 'Afrique', regions: [] },
  { code: 'NA', name: 'Namibie', flag: '🇳🇦', continent: 'Afrique', regions: [] },
  { code: 'UG', name: 'Ouganda', flag: '🇺🇬', continent: 'Afrique', regions: [] },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', continent: 'Afrique', regions: [] },
  { code: 'ST', name: 'Sao Tomé-et-Principe', flag: '🇸🇹', continent: 'Afrique', regions: [] },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', continent: 'Afrique', regions: [] },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', continent: 'Afrique', regions: [] },
  { code: 'SO', name: 'Somalie', flag: '🇸🇴', continent: 'Afrique', regions: [] },
  { code: 'SD', name: 'Soudan', flag: '🇸🇩', continent: 'Afrique', regions: [] },
  { code: 'SS', name: 'Soudan du Sud', flag: '🇸🇸', continent: 'Afrique', regions: [] },
  { code: 'TZ', name: 'Tanzanie', flag: '🇹🇿', continent: 'Afrique', regions: [] },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩', continent: 'Afrique', regions: [] },
  { code: 'ZM', name: 'Zambie', flag: '🇿🇲', continent: 'Afrique', regions: [] },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', continent: 'Afrique', regions: [] },

  // Europe
  { code: 'FR', name: 'France', flag: '🇫🇷', continent: 'Europe', regions: [] },
  { code: 'BE', name: 'Belgique', flag: '🇧🇪', continent: 'Europe', regions: [] },
  { code: 'CH', name: 'Suisse', flag: '🇨🇭', continent: 'Europe', regions: [] },
  { code: 'GB', name: 'Royaume-Uni', flag: '🇬🇧', continent: 'Europe', regions: [] },
  { code: 'DE', name: 'Allemagne', flag: '🇩🇪', continent: 'Europe', regions: [] },
  { code: 'ES', name: 'Espagne', flag: '🇪🇸', continent: 'Europe', regions: [] },
  { code: 'IT', name: 'Italie', flag: '🇮🇹', continent: 'Europe', regions: [] },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', continent: 'Europe', regions: [] },
  { code: 'AL', name: 'Albanie', flag: '🇦🇱', continent: 'Europe', regions: [] },
  { code: 'AD', name: 'Andorre', flag: '🇦🇩', continent: 'Europe', regions: [] },
  { code: 'AT', name: 'Autriche', flag: '🇦🇹', continent: 'Europe', regions: [] },
  { code: 'BY', name: 'Biélorussie', flag: '🇧🇾', continent: 'Europe', regions: [] },
  { code: 'BA', name: 'Bosnie-Herzégovine', flag: '🇧🇦', continent: 'Europe', regions: [] },
  { code: 'BG', name: 'Bulgarie', flag: '🇧🇬', continent: 'Europe', regions: [] },
  { code: 'CY', name: 'Chypre', flag: '🇨🇾', continent: 'Europe', regions: [] },
  { code: 'HR', name: 'Croatie', flag: '🇭🇷', continent: 'Europe', regions: [] },
  { code: 'DK', name: 'Danemark', flag: '🇩🇰', continent: 'Europe', regions: [] },
  { code: 'EE', name: 'Estonie', flag: '🇪🇪', continent: 'Europe', regions: [] },
  { code: 'FI', name: 'Finlande', flag: '🇫🇮', continent: 'Europe', regions: [] },
  { code: 'GR', name: 'Grèce', flag: '🇬🇷', continent: 'Europe', regions: [] },
  { code: 'HU', name: 'Hongrie', flag: '🇭🇺', continent: 'Europe', regions: [] },
  { code: 'IE', name: 'Irlande', flag: '🇮🇪', continent: 'Europe', regions: [] },
  { code: 'IS', name: 'Islande', flag: '🇮🇸', continent: 'Europe', regions: [] },
  { code: 'XK', name: 'Kosovo', flag: '🇽🇰', continent: 'Europe', regions: [] },
  { code: 'LV', name: 'Lettonie', flag: '🇱🇻', continent: 'Europe', regions: [] },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', continent: 'Europe', regions: [] },
  { code: 'LT', name: 'Lituanie', flag: '🇱🇹', continent: 'Europe', regions: [] },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', continent: 'Europe', regions: [] },
  { code: 'MK', name: 'Macédoine du Nord', flag: '🇲🇰', continent: 'Europe', regions: [] },
  { code: 'MT', name: 'Malte', flag: '🇲🇹', continent: 'Europe', regions: [] },
  { code: 'MD', name: 'Moldavie', flag: '🇲🇩', continent: 'Europe', regions: [] },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', continent: 'Europe', regions: [] },
  { code: 'ME', name: 'Monténégro', flag: '🇲🇪', continent: 'Europe', regions: [] },
  { code: 'NO', name: 'Norvège', flag: '🇳🇴', continent: 'Europe', regions: [] },
  { code: 'NL', name: 'Pays-Bas', flag: '🇳🇱', continent: 'Europe', regions: [] },
  { code: 'PL', name: 'Pologne', flag: '🇵🇱', continent: 'Europe', regions: [] },
  { code: 'CZ', name: 'République tchèque', flag: '🇨🇿', continent: 'Europe', regions: [] },
  { code: 'RO', name: 'Roumanie', flag: '🇷🇴', continent: 'Europe', regions: [] },
  { code: 'RU', name: 'Russie', flag: '🇷🇺', continent: 'Europe', regions: [] },
  { code: 'SM', name: 'Saint-Marin', flag: '🇸🇲', continent: 'Europe', regions: [] },
  { code: 'RS', name: 'Serbie', flag: '🇷🇸', continent: 'Europe', regions: [] },
  { code: 'SK', name: 'Slovaquie', flag: '🇸🇰', continent: 'Europe', regions: [] },
  { code: 'SI', name: 'Slovénie', flag: '🇸🇮', continent: 'Europe', regions: [] },
  { code: 'SE', name: 'Suède', flag: '🇸🇪', continent: 'Europe', regions: [] },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', continent: 'Europe', regions: [] },
  { code: 'VA', name: 'Vatican', flag: '🇻🇦', continent: 'Europe', regions: [] },

  // Amérique du Nord
  { code: 'CA', name: 'Canada', flag: '🇨🇦', continent: 'Amérique du Nord', regions: [] },
  { code: 'US', name: 'États-Unis', flag: '🇺🇸', continent: 'Amérique du Nord', regions: [] },
  { code: 'MX', name: 'Mexique', flag: '🇲🇽', continent: 'Amérique du Nord', regions: [] },

  // Amérique centrale & Caraïbes
  { code: 'AG', name: 'Antigua-et-Barbuda', flag: '🇦🇬', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'BB', name: 'Barbade', flag: '🇧🇧', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'DM', name: 'Dominique', flag: '🇩🇲', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'GD', name: 'Grenade', flag: '🇬🇩', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'HT', name: 'Haïti', flag: '🇭🇹', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'JM', name: 'Jamaïque', flag: '🇯🇲', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'DO', name: 'République dominicaine', flag: '🇩🇴', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'KN', name: 'Saint-Kitts-et-Nevis', flag: '🇰🇳', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'LC', name: 'Sainte-Lucie', flag: '🇱🇨', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', flag: '🇻🇨', continent: 'Amérique centrale & Caraïbes', regions: [] },
  { code: 'TT', name: 'Trinité-et-Tobago', flag: '🇹🇹', continent: 'Amérique centrale & Caraïbes', regions: [] },

  // Amérique du Sud
  { code: 'BR', name: 'Brésil', flag: '🇧🇷', continent: 'Amérique du Sud', regions: [] },
  { code: 'AR', name: 'Argentine', flag: '🇦🇷', continent: 'Amérique du Sud', regions: [] },
  { code: 'BO', name: 'Bolivie', flag: '🇧🇴', continent: 'Amérique du Sud', regions: [] },
  { code: 'CL', name: 'Chili', flag: '🇨🇱', continent: 'Amérique du Sud', regions: [] },
  { code: 'CO', name: 'Colombie', flag: '🇨🇴', continent: 'Amérique du Sud', regions: [] },
  { code: 'EC', name: 'Équateur', flag: '🇪🇨', continent: 'Amérique du Sud', regions: [] },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', continent: 'Amérique du Sud', regions: [] },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', continent: 'Amérique du Sud', regions: [] },
  { code: 'PE', name: 'Pérou', flag: '🇵🇪', continent: 'Amérique du Sud', regions: [] },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', continent: 'Amérique du Sud', regions: [] },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', continent: 'Amérique du Sud', regions: [] },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', continent: 'Amérique du Sud', regions: [] },

  // Moyen-Orient
  { code: 'AE', name: 'Émirats arabes unis', flag: '🇦🇪', continent: 'Moyen-Orient', regions: [] },
  { code: 'SA', name: 'Arabie saoudite', flag: '🇸🇦', continent: 'Moyen-Orient', regions: [] },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', continent: 'Moyen-Orient', regions: [] },
  { code: 'BH', name: 'Bahreïn', flag: '🇧🇭', continent: 'Moyen-Orient', regions: [] },
  { code: 'IQ', name: 'Irak', flag: '🇮🇶', continent: 'Moyen-Orient', regions: [] },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', continent: 'Moyen-Orient', regions: [] },
  { code: 'IL', name: 'Israël', flag: '🇮🇱', continent: 'Moyen-Orient', regions: [] },
  { code: 'JO', name: 'Jordanie', flag: '🇯🇴', continent: 'Moyen-Orient', regions: [] },
  { code: 'KW', name: 'Koweït', flag: '🇰🇼', continent: 'Moyen-Orient', regions: [] },
  { code: 'LB', name: 'Liban', flag: '🇱🇧', continent: 'Moyen-Orient', regions: [] },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', continent: 'Moyen-Orient', regions: [] },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', continent: 'Moyen-Orient', regions: [] },
  { code: 'SY', name: 'Syrie', flag: '🇸🇾', continent: 'Moyen-Orient', regions: [] },
  { code: 'YE', name: 'Yémen', flag: '🇾🇪', continent: 'Moyen-Orient', regions: [] },
  { code: 'TR', name: 'Turquie', flag: '🇹🇷', continent: 'Moyen-Orient', regions: [] },

  // Asie
  { code: 'CN', name: 'Chine', flag: '🇨🇳', continent: 'Asie', regions: [] },
  { code: 'IN', name: 'Inde', flag: '🇮🇳', continent: 'Asie', regions: [] },
  { code: 'JP', name: 'Japon', flag: '🇯🇵', continent: 'Asie', regions: [] },
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', continent: 'Asie', regions: [] },
  { code: 'AM', name: 'Arménie', flag: '🇦🇲', continent: 'Asie', regions: [] },
  { code: 'AZ', name: 'Azerbaïdjan', flag: '🇦🇿', continent: 'Asie', regions: [] },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', continent: 'Asie', regions: [] },
  { code: 'BT', name: 'Bhoutan', flag: '🇧🇹', continent: 'Asie', regions: [] },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', continent: 'Asie', regions: [] },
  { code: 'KH', name: 'Cambodge', flag: '🇰🇭', continent: 'Asie', regions: [] },
  { code: 'KP', name: 'Corée du Nord', flag: '🇰🇵', continent: 'Asie', regions: [] },
  { code: 'KR', name: 'Corée du Sud', flag: '🇰🇷', continent: 'Asie', regions: [] },
  { code: 'GE', name: 'Géorgie', flag: '🇬🇪', continent: 'Asie', regions: [] },
  { code: 'ID', name: 'Indonésie', flag: '🇮🇩', continent: 'Asie', regions: [] },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', continent: 'Asie', regions: [] },
  { code: 'KG', name: 'Kirghizistan', flag: '🇰🇬', continent: 'Asie', regions: [] },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', continent: 'Asie', regions: [] },
  { code: 'MY', name: 'Malaisie', flag: '🇲🇾', continent: 'Asie', regions: [] },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', continent: 'Asie', regions: [] },
  { code: 'MN', name: 'Mongolie', flag: '🇲🇳', continent: 'Asie', regions: [] },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', continent: 'Asie', regions: [] },
  { code: 'NP', name: 'Népal', flag: '🇳🇵', continent: 'Asie', regions: [] },
  { code: 'UZ', name: 'Ouzbékistan', flag: '🇺🇿', continent: 'Asie', regions: [] },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', continent: 'Asie', regions: [] },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', continent: 'Asie', regions: [] },
  { code: 'SG', name: 'Singapour', flag: '🇸🇬', continent: 'Asie', regions: [] },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', continent: 'Asie', regions: [] },
  { code: 'TW', name: 'Taïwan', flag: '🇹🇼', continent: 'Asie', regions: [] },
  { code: 'TJ', name: 'Tadjikistan', flag: '🇹🇯', continent: 'Asie', regions: [] },
  { code: 'TH', name: 'Thaïlande', flag: '🇹🇭', continent: 'Asie', regions: [] },
  { code: 'TL', name: 'Timor oriental', flag: '🇹🇱', continent: 'Asie', regions: [] },
  { code: 'TM', name: 'Turkménistan', flag: '🇹🇲', continent: 'Asie', regions: [] },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', continent: 'Asie', regions: [] },

  // Océanie
  { code: 'AU', name: 'Australie', flag: '🇦🇺', continent: 'Océanie', regions: [] },
  { code: 'FJ', name: 'Fidji', flag: '🇫🇯', continent: 'Océanie', regions: [] },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮', continent: 'Océanie', regions: [] },
  { code: 'MH', name: 'Îles Marshall', flag: '🇲🇭', continent: 'Océanie', regions: [] },
  { code: 'FM', name: 'Micronésie', flag: '🇫🇲', continent: 'Océanie', regions: [] },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷', continent: 'Océanie', regions: [] },
  { code: 'NZ', name: 'Nouvelle-Zélande', flag: '🇳🇿', continent: 'Océanie', regions: [] },
  { code: 'PW', name: 'Palaos', flag: '🇵🇼', continent: 'Océanie', regions: [] },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', flag: '🇵🇬', continent: 'Océanie', regions: [] },
  { code: 'SB', name: 'Salomon', flag: '🇸🇧', continent: 'Océanie', regions: [] },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', continent: 'Océanie', regions: [] },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', continent: 'Océanie', regions: [] },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', continent: 'Océanie', regions: [] },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', continent: 'Océanie', regions: [] },
]

export function findCountry(code) {
  return COUNTRIES.find((c) => c.code === code) || null
}

export function findRegion(countryCode, regionName) {
  return findCountry(countryCode)?.regions.find((r) => r.name === regionName) || null
}
