// Countries prioritized for BomaVibes' Francophone-Africa-first rollout.
// Adding a new country later is just appending an object here — no other
// code needs to change. `regions: []` is valid for a country not yet
// mapped in detail (the picker will simply skip straight to a free city
// entry for that country until regions are added).

export const COUNTRIES = [
  {
    code: 'GA',
    name: 'Gabon',
    flag: '🇬🇦',
    regions: [
      { name: 'Estuaire', cities: ['Libreville', 'Akanda', 'Owendo', 'Ntoum'] },
      { name: 'Haut-Ogooué', cities: ['Franceville', 'Moanda', 'Okondja'] },
      { name: 'Moyen-Ogooué', cities: ['Lambaréné', 'Ndjolé'] },
      { name: 'Ngounié', cities: ['Mouila', 'Fougamou', 'Mbigou'] },
      { name: 'Nyanga', cities: ['Tchibanga', 'Mayumba'] },
      { name: 'Ogooué-Ivindo', cities: ['Makokou', 'Booué', 'Mékambo'] },
      { name: 'Ogooué-Lolo', cities: ['Koulamoutou', 'Lastourville', 'Pana'] },
      { name: 'Ogooué-Maritime', cities: ['Port-Gentil', 'Gamba', 'Omboué'] },
      { name: 'Woleu-Ntem', cities: ['Oyem', 'Bitam', 'Mitzic'] },
    ],
  },
  {
    code: 'CM',
    name: 'Cameroun',
    flag: '🇨🇲',
    regions: [
      { name: 'Centre', cities: ['Yaoundé', 'Mbalmayo', 'Obala'] },
      { name: 'Littoral', cities: ['Douala', 'Nkongsamba', 'Édéa'] },
      { name: 'Ouest', cities: ['Bafoussam', 'Dschang', 'Mbouda'] },
      { name: 'Nord-Ouest', cities: ['Bamenda', 'Kumbo'] },
      { name: 'Sud-Ouest', cities: ['Buea', 'Limbe', 'Kumba'] },
      { name: 'Nord', cities: ['Garoua', 'Guider'] },
      { name: 'Extrême-Nord', cities: ['Maroua', 'Kousséri'] },
      { name: 'Adamaoua', cities: ['Ngaoundéré', 'Meiganga'] },
      { name: 'Est', cities: ['Bertoua', 'Abong-Mbang'] },
      { name: 'Sud', cities: ['Ebolowa', 'Kribi', 'Sangmélima'] },
    ],
  },
  {
    code: 'CG',
    name: 'Congo',
    flag: '🇨🇬',
    regions: [
      { name: 'Brazzaville', cities: ['Brazzaville'] },
      { name: 'Pointe-Noire', cities: ['Pointe-Noire'] },
      { name: 'Niari', cities: ['Dolisie', 'Loudima'] },
      { name: 'Bouenza', cities: ['Nkayi', 'Madingou'] },
      { name: 'Cuvette', cities: ['Owando', 'Boundji'] },
      { name: 'Cuvette-Ouest', cities: ['Ewo'] },
      { name: 'Kouilou', cities: ['Hinda', 'Madingo-Kayes'] },
      { name: 'Lékoumou', cities: ['Sibiti'] },
      { name: 'Likouala', cities: ['Impfondo', 'Dongou'] },
      { name: 'Plateaux', cities: ['Djambala', 'Gamboma'] },
      { name: 'Pool', cities: ['Kinkala', 'Mindouli'] },
      { name: 'Sangha', cities: ['Ouesso', 'Sembé'] },
    ],
  },
  {
    code: 'CD',
    name: 'RDC',
    flag: '🇨🇩',
    regions: [
      { name: 'Kinshasa', cities: ['Kinshasa'] },
      { name: 'Kongo-Central', cities: ['Matadi', 'Boma', 'Muanda'] },
      { name: 'Nord-Kivu', cities: ['Goma', 'Butembo', 'Beni'] },
      { name: 'Sud-Kivu', cities: ['Bukavu', 'Uvira'] },
      { name: 'Haut-Katanga', cities: ['Lubumbashi', 'Likasi', 'Kipushi'] },
      { name: 'Lualaba', cities: ['Kolwezi'] },
      { name: 'Kasaï', cities: ['Tshikapa'] },
      { name: 'Kasaï-Central', cities: ['Kananga'] },
      { name: 'Kasaï-Oriental', cities: ['Mbuji-Mayi'] },
      { name: 'Tshopo', cities: ['Kisangani'] },
      { name: 'Ituri', cities: ['Bunia'] },
      { name: 'Équateur', cities: ['Mbandaka'] },
    ],
  },
  {
    code: 'CI',
    name: "Côte d'Ivoire",
    flag: '🇨🇮',
    regions: [
      { name: 'Abidjan', cities: ['Abidjan'] },
      { name: 'Yamoussoukro', cities: ['Yamoussoukro'] },
      { name: 'Bas-Sassandra', cities: ['San-Pédro', 'Sassandra'] },
      { name: 'Comoé', cities: ['Abengourou', 'Agnibilékrou'] },
      { name: 'Denguélé', cities: ['Odienné'] },
      { name: 'Gôh-Djiboua', cities: ['Gagnoa', 'Divo'] },
      { name: 'Lacs', cities: ['Dimbokro', 'Bongouanou'] },
      { name: 'Lagunes', cities: ['Dabou', 'Grand-Bassam'] },
      { name: 'Montagnes', cities: ['Man', 'Danané'] },
      { name: 'Sassandra-Marahoué', cities: ['Daloa', 'Vavoua'] },
      { name: 'Savanes', cities: ['Korhogo', 'Ferkessédougou'] },
      { name: 'Vallée du Bandama', cities: ['Bouaké', 'Katiola'] },
      { name: 'Woroba', cities: ['Séguéla', 'Mankono'] },
      { name: 'Zanzan', cities: ['Bondoukou', 'Bouna'] },
    ],
  },
  {
    code: 'SN',
    name: 'Sénégal',
    flag: '🇸🇳',
    regions: [
      { name: 'Dakar', cities: ['Dakar', 'Pikine', 'Guédiawaye', 'Rufisque'] },
      { name: 'Thiès', cities: ['Thiès', 'Mbour', 'Tivaouane'] },
      { name: 'Diourbel', cities: ['Diourbel', 'Touba', 'Mbacké'] },
      { name: 'Saint-Louis', cities: ['Saint-Louis', 'Richard-Toll'] },
      { name: 'Louga', cities: ['Louga', 'Kébémer'] },
      { name: 'Fatick', cities: ['Fatick', 'Gossas'] },
      { name: 'Kaolack', cities: ['Kaolack', 'Guinguinéo'] },
      { name: 'Kaffrine', cities: ['Kaffrine'] },
      { name: 'Tambacounda', cities: ['Tambacounda'] },
      { name: 'Kédougou', cities: ['Kédougou'] },
      { name: 'Kolda', cities: ['Kolda'] },
      { name: 'Sédhiou', cities: ['Sédhiou'] },
      { name: 'Ziguinchor', cities: ['Ziguinchor'] },
      { name: 'Matam', cities: ['Matam'] },
    ],
  },
  {
    code: 'BJ',
    name: 'Bénin',
    flag: '🇧🇯',
    regions: [
      { name: 'Littoral', cities: ['Cotonou'] },
      { name: 'Atlantique', cities: ['Abomey-Calavi', 'Ouidah'] },
      { name: 'Ouémé', cities: ['Porto-Novo', 'Sèmè-Podji'] },
      { name: 'Plateau', cities: ['Sakété', 'Pobè'] },
      { name: 'Zou', cities: ['Abomey', 'Bohicon'] },
      { name: 'Collines', cities: ['Savalou', 'Dassa-Zoumè'] },
      { name: 'Borgou', cities: ['Parakou', 'Nikki'] },
      { name: 'Alibori', cities: ['Kandi', 'Malanville'] },
      { name: 'Atacora', cities: ['Natitingou', 'Tanguiéta'] },
      { name: 'Donga', cities: ['Djougou', 'Bassila'] },
      { name: 'Couffo', cities: ['Aplahoué', 'Dogbo'] },
      { name: 'Mono', cities: ['Lokossa', 'Comè'] },
    ],
  },
  {
    code: 'TG',
    name: 'Togo',
    flag: '🇹🇬',
    regions: [
      { name: 'Maritime', cities: ['Lomé', 'Aného', 'Tsévié'] },
      { name: 'Plateaux', cities: ['Atakpamé', 'Kpalimé'] },
      { name: 'Centrale', cities: ['Sokodé', 'Sotouboua'] },
      { name: 'Kara', cities: ['Kara', 'Bassar'] },
      { name: 'Savanes', cities: ['Dapaong', 'Mango'] },
    ],
  },
  {
    code: 'ML',
    name: 'Mali',
    flag: '🇲🇱',
    regions: [
      { name: 'Bamako', cities: ['Bamako'] },
      { name: 'Kayes', cities: ['Kayes', 'Kita'] },
      { name: 'Koulikoro', cities: ['Koulikoro', 'Kati'] },
      { name: 'Sikasso', cities: ['Sikasso', 'Koutiala'] },
      { name: 'Ségou', cities: ['Ségou', 'San'] },
      { name: 'Mopti', cities: ['Mopti', 'Djenné'] },
      { name: 'Tombouctou', cities: ['Tombouctou'] },
      { name: 'Gao', cities: ['Gao'] },
      { name: 'Kidal', cities: ['Kidal'] },
    ],
  },
  {
    code: 'BF',
    name: 'Burkina Faso',
    flag: '🇧🇫',
    regions: [
      { name: 'Centre', cities: ['Ouagadougou'] },
      { name: 'Hauts-Bassins', cities: ['Bobo-Dioulasso'] },
      { name: 'Boucle du Mouhoun', cities: ['Dédougou'] },
      { name: 'Cascades', cities: ['Banfora'] },
      { name: 'Centre-Est', cities: ['Tenkodogo'] },
      { name: 'Centre-Nord', cities: ['Kaya'] },
      { name: 'Centre-Ouest', cities: ['Koudougou'] },
      { name: 'Centre-Sud', cities: ['Manga'] },
      { name: 'Est', cities: ['Fada N\'Gourma'] },
      { name: 'Nord', cities: ['Ouahigouya'] },
      { name: 'Plateau-Central', cities: ['Ziniaré'] },
      { name: 'Sahel', cities: ['Dori'] },
      { name: 'Sud-Ouest', cities: ['Gaoua'] },
    ],
  },
  {
    code: 'NE',
    name: 'Niger',
    flag: '🇳🇪',
    regions: [
      { name: 'Niamey', cities: ['Niamey'] },
      { name: 'Agadez', cities: ['Agadez', 'Arlit'] },
      { name: 'Diffa', cities: ['Diffa'] },
      { name: 'Dosso', cities: ['Dosso'] },
      { name: 'Maradi', cities: ['Maradi'] },
      { name: 'Tahoua', cities: ['Tahoua', 'Birni-N\'Konni'] },
      { name: 'Tillabéri', cities: ['Tillabéri'] },
      { name: 'Zinder', cities: ['Zinder'] },
    ],
  },
  {
    code: 'MA',
    name: 'Maroc',
    flag: '🇲🇦',
    regions: [
      { name: 'Casablanca-Settat', cities: ['Casablanca', 'Settat', 'Mohammédia'] },
      { name: 'Rabat-Salé-Kénitra', cities: ['Rabat', 'Salé', 'Kénitra'] },
      { name: 'Fès-Meknès', cities: ['Fès', 'Meknès'] },
      { name: 'Marrakech-Safi', cities: ['Marrakech', 'Safi', 'Essaouira'] },
      { name: 'Tanger-Tétouan-Al Hoceïma', cities: ['Tanger', 'Tétouan'] },
      { name: 'Oriental', cities: ['Oujda', 'Nador'] },
      { name: 'Souss-Massa', cities: ['Agadir', 'Taroudant'] },
      { name: 'Béni Mellal-Khénifra', cities: ['Béni Mellal', 'Khénifra'] },
      { name: 'Drâa-Tafilalet', cities: ['Errachidia', 'Ouarzazate'] },
      { name: 'Guelmim-Oued Noun', cities: ['Guelmim'] },
      { name: 'Laâyoune-Sakia El Hamra', cities: ['Laâyoune'] },
      { name: 'Dakhla-Oued Ed-Dahab', cities: ['Dakhla'] },
    ],
  },
  {
    code: 'DZ',
    name: 'Algérie',
    flag: '🇩🇿',
    regions: [
      { name: 'Alger', cities: ['Alger', 'Bab Ezzouar', 'Hydra'] },
      { name: 'Oran', cities: ['Oran', 'Es Senia', 'Bir El Djir'] },
      { name: 'Constantine', cities: ['Constantine', 'El Khroub'] },
      { name: 'Annaba', cities: ['Annaba', 'El Bouni'] },
      { name: 'Blida', cities: ['Blida', 'Boufarik'] },
      { name: 'Tlemcen', cities: ['Tlemcen', 'Maghnia'] },
      { name: 'Sétif', cities: ['Sétif', 'El Eulma'] },
      { name: 'Béjaïa', cities: ['Béjaïa', 'Akbou'] },
      { name: 'Batna', cities: ['Batna', 'Barika'] },
      { name: 'Tizi Ouzou', cities: ['Tizi Ouzou', 'Azazga'] },
      { name: 'Ouargla', cities: ['Ouargla', 'Hassi Messaoud'] },
      { name: 'Ghardaïa', cities: ['Ghardaïa', 'Metlili'] },
    ],
  },
  {
    code: 'TN',
    name: 'Tunisie',
    flag: '🇹🇳',
    regions: [
      { name: 'Tunis', cities: ['Tunis'] },
      { name: 'Ariana', cities: ['Ariana'] },
      { name: 'Ben Arous', cities: ['Ben Arous'] },
      { name: 'Manouba', cities: ['Manouba'] },
      { name: 'Nabeul', cities: ['Nabeul', 'Hammamet'] },
      { name: 'Sousse', cities: ['Sousse'] },
      { name: 'Monastir', cities: ['Monastir'] },
      { name: 'Mahdia', cities: ['Mahdia'] },
      { name: 'Sfax', cities: ['Sfax'] },
      { name: 'Kairouan', cities: ['Kairouan'] },
      { name: 'Bizerte', cities: ['Bizerte'] },
      { name: 'Gabès', cities: ['Gabès'] },
      { name: 'Médenine', cities: ['Médenine', 'Djerba'] },
      { name: 'Tozeur', cities: ['Tozeur'] },
      { name: 'Gafsa', cities: ['Gafsa'] },
    ],
  },
  {
    code: 'NG',
    name: 'Nigeria',
    flag: '🇳🇬',
    regions: [
      { name: 'Lagos', cities: ['Lagos', 'Ikeja', 'Lekki'] },
      { name: 'Federal Capital Territory', cities: ['Abuja'] },
      { name: 'Kano', cities: ['Kano'] },
      { name: 'Rivers', cities: ['Port Harcourt'] },
      { name: 'Oyo', cities: ['Ibadan'] },
      { name: 'Kaduna', cities: ['Kaduna'] },
      { name: 'Ogun', cities: ['Abeokuta'] },
      { name: 'Enugu', cities: ['Enugu'] },
      { name: 'Delta', cities: ['Warri', 'Asaba'] },
      { name: 'Anambra', cities: ['Awka', 'Onitsha'] },
      { name: 'Edo', cities: ['Benin City'] },
      { name: 'Plateau', cities: ['Jos'] },
      { name: 'Borno', cities: ['Maiduguri'] },
      { name: 'Cross River', cities: ['Calabar'] },
    ],
  },
]

export function findCountry(code) {
  return COUNTRIES.find((c) => c.code === code) || null
}

export function findRegion(countryCode, regionName) {
  return findCountry(countryCode)?.regions.find((r) => r.name === regionName) || null
}
