// One-off generator for src/lib/cityCoords.js: looks up every city listed in
// src/lib/geography.js on OpenStreetMap Nominatim and writes a static
// { 'CC|City': [lat, lng] } table, so the app never geocodes at runtime.
//
// Re-run after adding cities to geography.js:
//   node scripts/geocodeCities.mjs
// Nominatim's usage policy allows at most 1 request/second — keep the delay.
import { writeFileSync } from 'node:fs'
import { COUNTRIES } from '../src/lib/geography.js'

const OUTPUT = new URL('../src/lib/cityCoords.js', import.meta.url)
const DELAY_MS = 1100

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

async function search(params) {
  const res = await fetch(`https://nominatim.openstreetmap.org/search?${params}&format=json&limit=1`, {
    headers: { 'User-Agent': 'bomavibes-geocoder (https://bomavibes.tech)' },
  })
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  const [hit] = await res.json()
  return hit ? [Number(Number(hit.lat).toFixed(4)), Number(Number(hit.lon).toFixed(4))] : null
}

// Structured city search first; free-text fallback for places OSM doesn't
// tag as a city (small towns, islands like Djerba).
async function geocode(city, country) {
  const structured = await search(`city=${encodeURIComponent(city)}&countrycodes=${country.code.toLowerCase()}`)
  if (structured) return structured
  await sleep(DELAY_MS)
  return search(`q=${encodeURIComponent(`${city}, ${country.name}`)}&countrycodes=${country.code.toLowerCase()}`)
}

const entries = []
const missing = []
for (const country of COUNTRIES) {
  for (const region of country.regions) {
    for (const city of region.cities) {
      try {
        const coords = await geocode(city, country)
        if (coords) entries.push([`${country.code}|${city}`, coords])
        else missing.push(`${country.code}|${city}`)
      } catch (err) {
        missing.push(`${country.code}|${city} (${err.message})`)
      }
      await sleep(DELAY_MS)
    }
  }
}

const body = entries.map(([key, [lat, lng]]) => `  ${JSON.stringify(key)}: [${lat}, ${lng}],`).join('\n')
writeFileSync(
  OUTPUT,
  `// Generated by scripts/geocodeCities.mjs from lib/geography.js — do not edit by hand.
// City-centre coordinates (OpenStreetMap Nominatim), keyed by 'COUNTRYCODE|City'.
export const CITY_COORDS = {
${body}
}
`,
)
console.log(`${entries.length} villes géocodées, ${missing.length} introuvables`)
if (missing.length) console.log(missing.join('\n'))
